# Generated by Django 5.1.14 on 2025-11-22 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_userexpensesummary_group_groupmember_group_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='user_groups', through='expenses.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
